### ISSUE TITLE
Make icon helper component

### ISSUE THREAD

**Issue by Kthulu120** [Kthulu120/ambrosia#12]
## Current Behavior

Currently we have to keep recurringly have to import icons over and over causing unneeded import statements. Instead if we had an Icon helper component we could minimize this static.

## Possible Solution
If we were to use this would be an example use case using all the props
```
<Icosia  height={32} width={32} color="white" icon_name="home">
```

Ideal Props:
height: string | number
width: string | number
icon_name: string: required
color: string

## TODO
- [ ] Make Icon helper
- [ ] Create official names for icons
- [ ] Add documentation in `docs` folder so that finding icons can be simple

**Comment by lamey** [comment]
@Kthulu120 Where do you want me to get the icons from, and where is the docs folder?

**Comment by Kthulu120** [comment]
@lamey  you'll need to create the `docs`. Also could you formulate the components for icons in Figma such as `x-circle`, `logo`, `plus-square` ...etc. Lift from [feather icons](https://feathericons.com/) if you can for the basic icons.
